# Generated by Django 2.2.7 on 2023-06-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0008_transferenciaaencuestalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCustomVarLog',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callid', models.CharField(db_index=True, max_length=32)),
                ('valor', models.CharField(max_length=128)),
            ],
        ),
    ]
